export const properties = {
  BRIDGE_ADDRESS_ROPSTEN: "ROPSTEN BRIDGE CONTRACT ADDRESS HERE",
  BRIDGE_ADDRESS_RINKEBY: "RINKEBY BRIDGE CONTRACT ADDRESS HERE",
  BRIDGE_ADDRESS_LOCAL: "LOCAL BRIDGE CONTRACT ADDRESS HERE",
  TEST_TOKEN_ADDRESS_ROPSTEN: "ROPSTEN TEST TOKEN CONTRACT ADDRESS HERE",
  TEST_TOKEN_ADDRESS_RINKEBY: "RINKEBY TEST TOKEN CONTRACT ADDRESS HERE",
  TEST_TOKEN_ADDRESS_LOCAL: "LOCAL TEST TOKEN CONTRACT ADDRESS HERE",
};
